// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Direct (non-pooled) connection for the CLI/migrations — Neon's pooled
    // endpoint runs PgBouncer in transaction mode, which doesn't support the
    // advisory locks Prisma Migrate needs. The app itself uses the pooled
    // DATABASE_URL at runtime — see src/lib/db.ts.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
